name: News

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r daily-news/requirements.txt
      - env:
          SEND_KEY: ${{ secrets.SEND_KEY }}
        run: |
          cd daily-news
          python daily_news.py
